<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Advert</title>
<script src="js/modernizr-2.5.2-respond-1.1.0.min.js" type="text/javascript"></script>
<script src="js/jquery-1.7.2.min.js" type="text/javascript"></script>
<script src="js/jquery.flexslider-min.js" type="text/javascript"></script>
<script src="js/jquery.mousewheel.js" type="text/javascript"></script>
<script src="js/jquery.easing.1.3.js" type="text/javascript"></script>
<script src="SpryAssets/SpryMenuBar.js" type="text/javascript"></script>
<link href="css/style.css" rel="stylesheet" type="text/css" />
<link href="css/flexslider.css" rel="stylesheet" type="text/css" />
<script type="text/xml">
<!--
<oa:widgets>
  <oa:widget wid="2827522" binding="#OAWidget" />
</oa:widgets>
-->
</script>
</head>
<style type="text/css">
.sidebar {
	width: 288px;
	height: auto;
	min-height: 600px;
	display: inline-block;
	background: #666;
	margin-right: 10px;
	vertical-align: top;
}
.taskpane {
	width: 860px;
	display: inline-block;
	background: #C7C7C7;
}
.header {
	background-color: #333333;
	height: 40px;
	width: 100%;
	min-width: 350px;
	position: fixed;
	z-index: 100;
	box-shadow: 0px 0px 25px #888888;
	font-family: Verdana, Geneva, sans-serif;
	font-size: 18px;
	color: #FFF;
}
 @charset "utf-8";
/* CSS Document */

html, body, div, span, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, abbr, address, cite, code, del, dfn, em, img, ins, kbd, q, samp, small, strong, sub, sup, var, b, i, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, figcaption, figure, footer, header, hgroup, menu, nav, section, summary, time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	outline: 0;
	font-size: 100%;
	vertical-align: baseline;
	background: transparent;
}
body {
	line-height: left;
}
article, aside, details, figcaption, figure, footer, header, hgroup, menu, nav, section {
	display: block;
}
nav ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after, q:before, q:after {
	content: '';
	content: none;
}
a {
	color: #FFF;
}
a:visited {
	color: #FFF;
	text-decoration: none;
}
a:hover {
	color: #CCC;
	text-decoration: underline;
}
a:active {
	color: #FFF;
	text-decoration: none;
}
a:link {
	text-decoration: none;
}
</style>
<body>
<script type="text/javascript">
// BeginOAWidget_Instance_2827522: #OAWidget
$(window).load(function() {
	 
	
      $('#slider').flexslider({
	    namespace: "flex-",             //{NEW} String: Prefix string attached to the class of every element generated by the plugin
    selector: ".slides > li",       //{NEW} Selector: Must match a simple pattern. '{container} > {slide}' -- Ignore pattern at your own peril
      animation: "slide",
	   easing: "swing",               //{NEW} String: Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!	
      direction: "horizontal",   //String: Select the sliding direction, 'horizontal' or 'vertical'
    reverse: false,                 //{NEW} Boolean: Reverse the animation direction
    animationLoop: true,             //Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
    smoothHeight: true,            //{NEW} Boolean: Allow height of the slider to animate smoothly in horizontal mode   
      slideshow: true,                //Boolean: Animate slider automatically
      slideshowSpeed: 5000,           //Integer: Set the speed of the slideshow cycling, in milliseconds
      animationSpeed: 600,         //Integer: Set the speed of animations, in milliseconds  
      initDelay: 0,                   //{NEW} Integer: Set an initialization delay, in milliseconds
      randomize: true,               //Boolean: Randomize slide order
	   useCSS: true,                   //{NEW} Boolean: Slider will use CSS3 transitions if available
      touch: true,                    //{NEW} Boolean: Allow touch swipe navigation of the slider on touch-enabled devices
       video: false,                   //{NEW} Boolean: If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches
      directionNav: false,             //Boolean: Create navigation for previous/next navigation? (true/false)
	  
      controlNav: true,               //Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage
      keyboard: true,              //Boolean: Allow slider navigating via keyboard left/right keys
      mousewheel: false,              //Boolean: Allow slider navigating via mousewheel
      prevText: "Previous",           //String: Set the text for the "previous" directionNav item
      nextText: "Next",               //String: Set the text for the "next" directionNav item
      pausePlay: false,               //Boolean: Create pause/play dynamic element
      pauseText: "Pause",             //String: Set the text for the "pause" pausePlay item
      playText: "Play",               //String: Set the text for the "play" pausePlay item
      startAt: 0,                //Integer: The slide that the slider should start on. Array notation (0 = first slide)
      pauseOnAction: true,            //Boolean: Pause the slideshow when interacting with control elements, highly recommended.
      pauseOnHover: true,            //Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering     
      start: function(){},            //Callback: function(slider) - Fires when the slider loads the first slide
	  controlsContainer: "",          //Selector: Declare which container the navigation elements should be appended too. Default container is the flexSlider element. Example use would be ".flexslider-container", "#container", etc. If the given element is 		                                        not found, the default action will be taken.
       manualControls: "",             //Selector: Declare custom control navigation. Example would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
       // Carousel Options
    itemWidth: 0,                   //{NEW} Integer: Box-model width of individual carousel items, including horizontal borders and padding.
    itemMargin: 10,                  //{NEW} Integer: Margin between carousel items.
    minItems: 0,                    //{NEW} Integer: Minimum number of carousel items that should be visible. Items will resize fluidly when below this.
    maxItems: 0,                    //{NEW} Integer: Maxmimum number of carousel items that should be visible. Items will resize fluidly when above this limit.
    move: 0,                        //{NEW} Integer: Number of carousel items that should move on animation. If 0, slider will move all visible items.
	  before: function(){},           //Callback: function(slider) - Fires asynchronously with each slider animation
      after: function(){},            //Callback: function(slider) - Fires after each slider animation completes
      end: function(){}               //Callback: function(slider) - Fires when the slider reaches the last slide (asynchronous)
      });
      });
// EndOAWidget_Instance_2827522
</script>
<div class="header">
  <div style="padding:4px; padding-bottom:0px; float:left;"> <img src="images/logo_fox.png" width="35" height="35" alt="LOGO" /> </div>
  <div style="padding:8px; padding-bottom:0px; float:left;"> FOXENTRY <font style="font-size:9px">beta</font> | <font style="font-size:9px">Powered by CSC CICT & LOOP</font> </div>
  <div style="padding:8px; padding-bottom:0px; padding-right:15px;" align="right">For Printing, Just insert your flash drive | Send us feedback! | <a href="logout.php">Sign In <img src="images/LH2-Shutdown-icon.png" width="20" height="20" vspace="8" /></a> </div>
</div>
<div style="width:100%; height:30px;"> </div>
<div id="main-container">
  <div id="main" class="wrapper clearfix">
    <div> </div>
    <div id="container">
      <div id="slider" class="flexslider">
        <ul class="slides">
          <?php
		error_reporting(E_ERROR);
		include('account/conn2.php');
		$result3 = mysqli_query($con,"SELECT * FROM fox_files WHERE type ='advert'");
		while($row3 = mysqli_fetch_array($result3))
  		{
 		echo '<li><img src="data:image/jpeg;base64,' . base64_encode($row3['data']) . '"></li>';
  		}
		?>
        </ul>
      </div>
    </div>
  </div>
  <!-- #main --> 
</div>
<!-- #main-container --> 

<script type="text/javascript">
var MenuBar1 = new Spry.Widget.MenuBar("MenuBar1", {imgDown:"SpryAssets/SpryMenuBarDownHover.gif", imgRight:"SpryAssets/SpryMenuBarRightHover.gif"});
</script>
</body>
</html>