<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Foxentry | Help Page and FAQs</title>
<script src="js/modernizr-2.5.2-respond-1.1.0.min.js" type="text/javascript"></script>
<script src="js/jquery-1.7.2.min.js" type="text/javascript"></script>
<script src="js/jquery.flexslider-min.js" type="text/javascript"></script>
<script src="js/jquery.mousewheel.js" type="text/javascript"></script>
<script src="js/jquery.easing.1.3.js" type="text/javascript"></script>
<script src="SpryAssets/SpryMenuBar.js" type="text/javascript"></script>
<link href="css/style.css" rel="stylesheet" type="text/css" />
<link href="css/flexslider.css" rel="stylesheet" type="text/css" />
<link rel="shortcut icon" href="images/logo_fox.ico" />
<script type="text/xml">
<!--
<oa:widgets>
  <oa:widget wid="2827522" binding="#OAWidget" />
</oa:widgets>
-->
</script>
</head>
<style type="text/css">
.sidebar {
	width: 288px;
	height: auto;
	min-height: 600px;
	display: inline-block;
	background: #666;
	margin-right: 10px;
	vertical-align: top;
}
.taskpane {
	width: 860px;
	display: inline-block;
	background: #C7C7C7;
}
.header {
	background-color: #333333;
	height: 40px;
	width: 100%;
	min-width: 350px;
	position: fixed;
	z-index: 100;
	box-shadow: 0px 0px 25px #888888;
	font-family: Verdana, Geneva, sans-serif;
	font-size: 18px;
	color: #FFF;
}

html, body, div, span, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, abbr, address, cite, code, del, dfn, em, img, ins, kbd, q, samp, small, strong, sub, sup, var, b, i, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, figcaption, figure, footer, header, hgroup, menu, nav, section, summary, time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	outline: 0;
	font-size: 100%;
	vertical-align: baseline;
	background: transparent;
}
body {
	line-height: left;
}
article, aside, details, figcaption, figure, footer, header, hgroup, menu, nav, section {
	display: block;
}
nav ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after, q:before, q:after {
	content: '';
	content: none;
}
a {
	color: #FFF;
}
a:visited {
	color: #FFF;
	text-decoration: none;
}
a:hover {
	color: #CCC;
	text-decoration: underline;
}
a:active {
	color: #FFF;
	text-decoration: none;
}
a:link {
	text-decoration: none;
}
em {
	color:#F60;
}
</style>
<body>
<script type="text/javascript">
// BeginOAWidget_Instance_2827522: #OAWidget
$(window).load(function() {
	 
	
      $('#slider').flexslider({
	    namespace: "flex-",             //{NEW} String: Prefix string attached to the class of every element generated by the plugin
    selector: ".slides > li",       //{NEW} Selector: Must match a simple pattern. '{container} > {slide}' -- Ignore pattern at your own peril
      animation: "slide",
	   easing: "swing",               //{NEW} String: Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!	
      direction: "horizontal",   //String: Select the sliding direction, 'horizontal' or 'vertical'
    reverse: false,                 //{NEW} Boolean: Reverse the animation direction
    animationLoop: true,             //Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
    smoothHeight: true,            //{NEW} Boolean: Allow height of the slider to animate smoothly in horizontal mode   
      slideshow: true,                //Boolean: Animate slider automatically
      slideshowSpeed: 5000,           //Integer: Set the speed of the slideshow cycling, in milliseconds
      animationSpeed: 600,         //Integer: Set the speed of animations, in milliseconds  
      initDelay: 0,                   //{NEW} Integer: Set an initialization delay, in milliseconds
      randomize: true,               //Boolean: Randomize slide order
	   useCSS: true,                   //{NEW} Boolean: Slider will use CSS3 transitions if available
      touch: true,                    //{NEW} Boolean: Allow touch swipe navigation of the slider on touch-enabled devices
       video: false,                   //{NEW} Boolean: If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches
      directionNav: false,             //Boolean: Create navigation for previous/next navigation? (true/false)
	  
      controlNav: true,               //Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage
      keyboard: true,              //Boolean: Allow slider navigating via keyboard left/right keys
      mousewheel: false,              //Boolean: Allow slider navigating via mousewheel
      prevText: "Previous",           //String: Set the text for the "previous" directionNav item
      nextText: "Next",               //String: Set the text for the "next" directionNav item
      pausePlay: false,               //Boolean: Create pause/play dynamic element
      pauseText: "Pause",             //String: Set the text for the "pause" pausePlay item
      playText: "Play",               //String: Set the text for the "play" pausePlay item
      startAt: 0,                //Integer: The slide that the slider should start on. Array notation (0 = first slide)
      pauseOnAction: true,            //Boolean: Pause the slideshow when interacting with control elements, highly recommended.
      pauseOnHover: true,            //Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering     
      start: function(){},            //Callback: function(slider) - Fires when the slider loads the first slide
	  controlsContainer: "",          //Selector: Declare which container the navigation elements should be appended too. Default container is the flexSlider element. Example use would be ".flexslider-container", "#container", etc. If the given element is 		                                        not found, the default action will be taken.
       manualControls: "",             //Selector: Declare custom control navigation. Example would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
       // Carousel Options
    itemWidth: 0,                   //{NEW} Integer: Box-model width of individual carousel items, including horizontal borders and padding.
    itemMargin: 10,                  //{NEW} Integer: Margin between carousel items.
    minItems: 0,                    //{NEW} Integer: Minimum number of carousel items that should be visible. Items will resize fluidly when below this.
    maxItems: 0,                    //{NEW} Integer: Maxmimum number of carousel items that should be visible. Items will resize fluidly when above this limit.
    move: 0,                        //{NEW} Integer: Number of carousel items that should move on animation. If 0, slider will move all visible items.
	  before: function(){},           //Callback: function(slider) - Fires asynchronously with each slider animation
      after: function(){},            //Callback: function(slider) - Fires after each slider animation completes
      end: function(){}               //Callback: function(slider) - Fires when the slider reaches the last slide (asynchronous)
      });
      });
// EndOAWidget_Instance_2827522
</script>
<div class="header">
  <div style="padding:4px; padding-bottom:0px; float:left;"> <img src="images/logo_fox.png" width="35" height="35" alt="LOGO" /> </div>
  <div style="padding:8px; padding-bottom:0px; float:left;"> <a href="/foxentry"> FOXENTRY <font style="font-size:9px">beta</font> | <font style="font-size:9px">Powered by CSC CICT & LOOP</font> </a></div>
  <div style="padding:8px; padding-bottom:0px; padding-right:15px;" align="right">Send us feedback! | <a href="logout.php">Sign In <img src="images/LH2-Shutdown-icon.png" width="20" height="20" vspace="8" /></a> </div>
</div>
<div style="width:100%; height:30px;"> </div>
<div id="main-container" style="width:1100px; margin:auto">
  <div id="main" class="wrapper clearfix">
    <div> </div>
    <div id="container">
      <p><strong>
      <h2>Welcome to Foxentry Help Page and FAQs' Page [Mabuhay! Ang pahinang ito ay para sa mga katanungang patungkol sa Foxentry]</h2></strong></p>
      <p>&nbsp;</p>
      <p>In this page are the most Frequently Asked Questions about Foxentry and Contact Information of Developers.</p>
      <p>&nbsp;</p>
      <p><em>1. What is Foxentry?</em><br />
        - Foxentry is a web application.
        It will serve as  the student portal for CICT students.
        It’s not a social networking site (for now).</p>
      <p><br />
      </p>
      <p><em>2. What is its Vission for the College?</em></p>
      <p>-In the future, the foxentry will become a tool for the student council, including the college organizations, for information dissemination in the college, including managing seminars, tutorials, special events and registration. <br />
      -Also, this project is one of the solution to lessen the use of paper. The advertisements posted in the webpage can also pave way for organizations to earn. </p>
      <p>&nbsp;</p>
      <p><em>3. How can you have an account?</em></p>
      <p>- All CICT Students are entitled to have an account. However, only the College Student Council and Organization Officers have the power to create user accounts. If you do not have an account, you can request for a creation of your account by going to the Student Council Office at SJH 103 CICT cubicle. Or you can also email us at (foxentrydev@gmail.com) for the creation of your account.  Upon requesting for the creation of your account, please include the following information: Full Name; Student Number; Section; Email Address; Contact Number, Course and Specialization, Section and an image of your HAU ID. Most upper year level students already have their account created during the enrolment. To verify if you already have an account, or to check your username, please use the form below. </p>
      <p>&nbsp;</p>
      <?php error_reporting(E_ERROR); ?>
      <form name="frmSearch" method="get" action="<?php $_SERVER['SCRIPT_NAME'] ?>">
        <table width="100%" border="0">
          <tr>
            <th>Enter your email address or Student Number 
              <input name="txtKeyword" type="text" id="txtKeyword" autocomplete="off" value="<?php $_GET["txtKeyword"];?>">
              <input type="submit" value="Check Now"></th>
          </tr>
        </table>
      </form>
      <?php
		session_start();
		if($_GET["txtKeyword"] != "")  
		{  
		include('this.php'); 
		include('joking.php'); 
		$key =  $_GET["txtKeyword"];
		$key = make_safe($key);
		$strSQL = "SELECT * FROM fox_users WHERE email = '".$key."' OR stdno = '".$key."' LIMIT 1"; 
		$objQuery = mysql_query($strSQL) or die ("Error Query [".$strSQL."]");
		$Num_Rows = mysql_num_rows($objQuery);  
		if ($Num_Rows > 0){
		while($objResult = mysql_fetch_array($objQuery))  

		{  
			if (md5($objResult['uname']) == $objResult['pword'])
			{
				echo "<p><center> Your Username is: <span style='color:red'>" . $objResult['uname'] . "</span><br/>Your Password is similar with your username. Please take note that the password is case sensitive.</center></p>";
			}
			else
			{
				echo "<p><center> Your Username is: <span style='color:red'>" . $objResult['uname'] . "</span><br/>It seems like your default password has been changed already.</center></p>";
			}
		}
		}
		else{
			echo "<center>Email Address/Student Number Not Registered</center>";
		}
		}

?>

<br>
      <p><em>4. I forgot my password. How can I reset it?</em></p>
      <p>- You can request for the reset of your password by sending an email to (foxentrydev@gmail.com). Use "Password Reset" as the subject of your email. Please include your Fullname, Student Number and Contact Number in the email. Please use the registered email address when requesting for recovery of your password. Also, you can go to the Student Council Office at SJH 103 for the reset of your password.</p>
      <p>&nbsp;</p>
      <p><em>5. I want to be a developer of this site. How can I apply.</em></p>
      <p>- Just log in your account and on the "Personal" tab, click “<a href="csccicthau.com/foxentry/index.php?p=dev" style="background-color:#F60; padding:3px;">Apply as Developer</a>”. Fill up the form and we will be contacting you as soon as we receive your application.</p>
      <p>&nbsp;</p>
      <p><em>6. I want to advertise on your website.</em></p>
      <p>- For advertisements in the website, you can contact us through email at (haucsccict1415@gmail.com).</p>
      <p>&nbsp;</p>
      <p><em>7. I noticed that the background of the login page differs every time and certain photographs are featured. How can I submit my own photograph?</em></p>
      <p>- Yes, the web application features different photos as background image of the login page. Most of the photos are taken or were submitted by the CICT students. You can send your photo by emailing us at (haucsccict1415@gmail.com) Use "Login BG" as the email subject.</p>
      <p>&nbsp;</p>
      <p><em>8. What happens when I submit a bullying report?</em></p>
      <p>- Bullying reports sent by students are evaluated by the Student Council officers. After the evaluation, the person who sent the report will be contacted by the council. If deemed necessary, the Student Council will relay the report to the Guidance office. </p>
      <p>&nbsp;</p>
      <p><em>9. What happens when I report a Professor?</em></p>
      <p>- Submitted reports about instructors/professors will be evaluated by the Student Council. After the evaluation, a consultation will be set by the Council together with the Student Council adviser and the College Program Chairperson. Your identity will remain anonymous and will not be disclosed to the instructor/professor reported.</p>
      <p>&nbsp;</p>
      <p><em>10. How can we contact your developers?</em></p>
      <p>- You can reach the developers through haucsccict1415@gmail.com. You can check the developers page here.</p>
      <p>&nbsp;</p>
      <center>
      <span style="font-size:11px">
      <p>(C) 2014 College Student Council - College of Information and Communications Technology<br />
        Holy Angel University<br />
        Code Geeks | League of Outstanding Programmers | Cisco Student Organization | The Access Point</p>
      </span>
      </center>
    </div>
  </div>
  <!-- #main --> 
</div>
<!-- #main-container --> 

<script type="text/javascript">
var MenuBar1 = new Spry.Widget.MenuBar("MenuBar1", {imgDown:"SpryAssets/SpryMenuBarDownHover.gif", imgRight:"SpryAssets/SpryMenuBarRightHover.gif"});
</script>
</body>
</html>