                        <div class="col-sm-5">
                           
							             <!-- Own Badge-->
                             <?php include("dashboard/badge.php"); ?>
                             <!-- End Badge-->
                             
                             <!-- Update Ticker-->
                             <?php include("dashboard/updates.php"); ?>
                             <!-- End Update Ticker-->
                             
                             <!-- News Feed-->
                             <?php // include("dashboard/dash-title.php"); ?>
                             <!-- End NEws Feed-->
                           
                             <!-- latest events-->
                             <?php include("dashboard/events.php"); ?>
                             <!-- End latest events-->
                           
                             <!-- ads -->
                             <?php include("dashboard/ads.php"); ?>
                             <!-- End ads-->
							                                               		
                           
                          </div>
                          
                          <!-- main col right -->
                          <div class="col-sm-7">
                               
                             <!-- news feeds -->
                             <?php include("dashboard/feeds.php"); ?>
                             <!-- End news feeds-->
							 
                             <!-- news feeds -->
                             <?php // include("dashboard/feature.php"); ?>
                             <!-- End news feeds-->
							  

                               
                            
                               
                            
                          </div>