<div style="float:right; margin-right:420px; margin-top:-12px">
	<div class="contain">
    <ul id="notificationMenu" class="notifications">
      <li class="titlebar">
        <span class="title">Notifications</span>
        <span class="settings">
        </span>
      </li>
      <div class="notifbox">
        <?php echo shownotifs($member_id); ?>
      </div>
      <li class="seeall">
        <a href="#">See All</a>
      </li>
    </ul>
  </div>
  </div>